AllCops:
  TargetRubyVersion: 2.3
Rails:
  Enabled: true

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Lint/Debugger:
  Severity: fatal

Style/StringLiterals:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Rails/TimeZone:
  Severity: warning

Rails/Date:
  Severity: warning

Style/ClassAndModuleChildren:
  Enabled: false

Style/Next:
  Enabled: false

Rails/ActionFilter:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Style/LeadingCommentSpace:
  Enabled: false

Style/EmptyLinesAroundClassBody:
  Enabled: false

Style/EmptyLinesAroundModuleBody:
  Enabled: false
