language: ruby
services:
  - postgresql

before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres

script:
  - RAILS_ENV=test bundle exec rake spec

